sudo: required
language: bash
env:
  global:
    - IMAGE_NAME=gableroux/unity3d:2018.3.7f1
    - BUILD_NAME=Ego-Trip
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_e7084cefba4a_key -iv $encrypted_e7084cefba4a_iv
    -in Unity_v2018.x.ulf.enc -out ./Unity_v2018.x.ulf -d
  - export UNITY_LICENSE_CONTENT=`cat Unity_v2018.x.ulf`
  - rm Unity_v2018.x.ulf
  - docker pull $IMAGE_NAME
  - sudo apt-get install zip
jobs:
  include:
    - stage: build
      env: BUILD_TARGET=StandaloneLinux64
      script: "chmod +x ./ci/* && ./ci/docker_build.sh && ./ci/docker_build.sh"
      addons:
        artifacts:
          debug: true
          target_paths:
            - "./Builds/"
    - stage: build
      env: BUILD_TARGET=StandaloneOSX
      script: "chmod +x ./ci/* && ./ci/docker_build.sh && ./ci/docker_build.sh"
      addons:
        artifacts:
          debug: true
          target_paths:
            - "./Builds/"
    - stage: build
      env: BUILD_TARGET=StandaloneWindows64
      script:
        - "chmod +x ./ci/before_script.sh && ./ci/docker_build.sh "
        - "zip -r StandaloneWindows64.zip ./Builds/StandaloneWindows64/"
      deploy:
        provider: releases
        api_key: $GITHUB_API_KEY
        file: StandaloneWindows64.zip
        skip_cleanup: true
        on:
          tags: true
    - stage: build
      env: BUILD_TARGET=WebGL
      script: "chmod +x ./ci/* && ./ci/docker_build.sh && ./ci/docker_build.sh"
      addons:
        artifacts:
          debug: true
          target_paths:
            - "./Builds/"
